#ifndef GCL_OPENMESHALGORITHMS_EXPORT_H
#define GCL_OPENMESHALGORITHMS_EXPORT_H
#include <qglobal.h>
#ifdef GCL_EXPORT_SHARED_LIB
#   ifdef GCL_OPENMESHALGORITHMS_SHARED_LIB
#       define GCL_OPENMESHALGORITHMS_SHARED_EXPORT Q_DECL_EXPORT
#   else
#       define GCL_OPENMESHALGORITHMS_SHARED_EXPORT Q_DECL_IMPORT
#   endif
#else
#   define GCL_OPENMESHALGORITHMS_SHARED_EXPORT
#endif

#endif // GCL_EXPORT_H
